In [3]:
import numpy as np
import pandas as pd

<h2>NumPy array creation via numpy.array</h2>

In [5]:
ar1 = np.array([0,1,2,3]) # 1 dimensional array

In [7]:
ar2=np.array([[0,3,5],[2,8,7]]) # 2D array

In [8]:
ar1

array([0, 1, 2, 3])

In [9]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

<b>Shape of the array</b>

In [10]:
ar2.shape

(2, 3)

<b>Number of dimensions</b>

In [13]:
ar2.ndim

2

<h2>NumPy array creation via numpy.arange</h2>

In [14]:
ar3=np.arange(12);ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
# start, end (exclusive)
ar4=np.arange(3,10,3);ar4

array([3, 6, 9])

<h2>NumPy array creation via numpy.linspace</h2>

In [16]:
# args - start element,end element, number of elements
ar5=np.linspace(0,2.0/3,4); ar5

array([ 0.        ,  0.22222222,  0.44444444,  0.66666667])

<h2>NumPy array via various other functions</h2>

<h3>numpy.ones</h3>

In [17]:
# Produces 2x3x2 array of 1's.
ar7=np.ones((2,3,2)); ar7

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

<h3>numpy.zeros</h3>

In [18]:
# Produce 4x2 array of zeros.
ar8=np.zeros((4,2));ar8

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [3]:
f_ar = np.array([3,-2,8.18])
f_ar

array([ 3.  , -2.  ,  8.18])

In [4]:
f_ar.astype(int)

array([ 3, -2,  8])

In [5]:
f_ar[5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [6]:
ar = np.array([0,1,2])

In [7]:
ar[5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [8]:
ar[1,3]

IndexError: too many indices for array

In [9]:
ar[[1,3]]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [10]:
ar[[1,2]]

array([1, 2])

In [11]:
ar[[0,2]]

array([0, 2])

In [13]:
ar=np.array([2,-16,7,5])

In [14]:
ar[[0,2]]

array([2, 7])

In [15]:
ar[0,2]

IndexError: too many indices for array

In [16]:
ar

array([  2, -16,   7,   5])

In [17]:
ar=np.arange(15); ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
ar2=np.arange(0,-10,-1)[::-1]; ar2

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])

In [19]:
ar[:10]=ar2; ar


array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0, 10, 11, 12, 13, 14])

In [21]:
ar=np.arange(0,6)
ar2=np.array([0,1,2,3,4,5])
np.array_equal(ar, ar2)


True

In [22]:
ar==ar2

array([ True,  True,  True,  True,  True,  True], dtype=bool)

In [24]:
np.all(ar==ar2)

True

In [25]:
np.random.seed(10)
ar=np.random.randint(0,10, size=(4,5));ar


array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0],
       [4, 6, 8, 1, 8]])

In [27]:
np.shape(ar)

(4, 5)

In [29]:
c_ar=np.cumsum(ar)

In [30]:
np.shape(c_ar)

(20,)

In [31]:
c_ar

array([ 9, 13, 13, 14, 23, 23, 24, 32, 41, 41, 49, 55, 59, 62, 62, 66, 72,
       80, 81, 89])

In [34]:
ar=np.arange(5); 
ar

array([0, 1, 2, 3, 4])

In [35]:
ar2=ar

In [36]:
ar.resize((8,));

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [38]:
np.resize(ar,(8,))

array([0, 1, 2, 3, 4, 0, 1, 2])

In [43]:
ar=np.array([[3,2],[10,-1]])
ar


array([[ 3,  2],
       [10, -1]])

In [44]:
ar.sort(axis=1)
ar

array([[ 2,  3],
       [-1, 10]])

In [45]:
ar=np.array([[3,2],[10,-1]])
ar

array([[ 3,  2],
       [10, -1]])

In [46]:
ar.sort(axis=0)
ar

array([[ 3, -1],
       [10,  2]])

In [48]:
ar=np.array([[3,2],[10,-1],[5,4]])
ar

array([[ 3,  2],
       [10, -1],
       [ 5,  4]])

In [49]:
currDict={'US' : 'dollar', 'UK' : 'pound', 
                    'Germany': 'euro', 'Mexico':'peso',
                    'Nigeria':'naira',
                    'China':'yuan', 'Japan':'yen'}
currSeries=pd.Series(currDict); currSeries


China        yuan
Germany      euro
Japan         yen
Mexico       peso
Nigeria     naira
UK          pound
US         dollar
dtype: object

In [50]:
currSeries.index

Index([u'China', u'Germany', u'Japan', u'Mexico', u'Nigeria', u'UK', u'US'], dtype='object')

In [51]:
type(currSeries.index)

pandas.core.index.Index

In [73]:
np.random.seed(2)
ser=pd.Series(np.random.rand(7)); ser

0    0.435995
1    0.025926
2    0.549662
3    0.435322
4    0.420368
5    0.330335
6    0.204649
dtype: float64

In [89]:
for i in range(3000001,4000000):
    np.random.seed(i)
    ser=pd.Series(np.random.rand(7))
    if abs(ser[0]-0.816225) < 0.0005 and abs(ser[1]-0.274074) < 0.0005:
        print "i=%s" %i 
        print ser
        print ser[0]
        break

i=3254441
0    0.816680
1    0.274298
2    0.029621
3    0.839700
4    0.150357
5    0.697690
6    0.652894
dtype: float64
0.816680178218


In [91]:
np.random.seed(100)
ser=pd.Series(np.random.rand(7)); ser

0    0.543405
1    0.278369
2    0.424518
3    0.844776
4    0.004719
5    0.121569
6    0.670749
dtype: float64

In [92]:
ser*ser

0    0.295289
1    0.077490
2    0.180215
3    0.713647
4    0.000022
5    0.014779
6    0.449904
dtype: float64

In [93]:
np.sqrt(ser)

0    0.737160
1    0.527607
2    0.651550
3    0.919117
4    0.068694
5    0.348668
6    0.818993
dtype: float64

In [94]:
ser[1:]

1    0.278369
2    0.424518
3    0.844776
4    0.004719
5    0.121569
6    0.670749
dtype: float64

In [95]:
ser[1:] + ser[:-2]

0         NaN
1    0.556739
2    0.849035
3    1.689552
4    0.009438
5         NaN
6         NaN
dtype: float64

In [96]:
ser

0    0.543405
1    0.278369
2    0.424518
3    0.844776
4    0.004719
5    0.121569
6    0.670749
dtype: float64

In [97]:
stockSummaries={
'AMZN': pd.Series([346.15,0.59,459,0.52,589.8,158.88], 
        index=['Closing price','EPS',
                'Shares Outstanding(M)',
                'Beta', 'P/E','Market Cap(B)']),
'GOOG': pd.Series([1133.43,36.05,335.83,0.87,31.44,380.64],
        index=['Closing price','EPS','Shares  Outstanding(M)',
               'Beta','P/E','Market Cap(B)']),
'FB': pd.Series([61.48,0.59,2450,104.93,150.92], 
      index=['Closing price','EPS','Shares Outstanding(M)',
             'P/E', 'Market Cap(B)']),
'YHOO': pd.Series([34.90,1.27,1010,27.48,0.66,35.36],
        index=['Closing price','EPS','Shares Outstanding(M)',
               'P/E','Beta', 'Market Cap(B)']),
'TWTR':pd.Series([65.25,-0.3,555.2,36.23],
       index=['Closing price','EPS','Shares Outstanding(M)',
              'Market Cap(B)']), 
'AAPL':pd.Series([501.53,40.32,892.45,12.44,447.59,0.84],
       index=['Closing price','EPS','Shares Outstanding(M)','P/E',   
              'Market Cap(B)','Beta'])}


In [98]:
stockSummaries

{'AAPL': Closing price            501.53
 EPS                       40.32
 Shares Outstanding(M)    892.45
 P/E                       12.44
 Market Cap(B)            447.59
 Beta                       0.84
 dtype: float64, 'AMZN': Closing price            346.15
 EPS                        0.59
 Shares Outstanding(M)    459.00
 Beta                       0.52
 P/E                      589.80
 Market Cap(B)            158.88
 dtype: float64, 'FB': Closing price              61.48
 EPS                         0.59
 Shares Outstanding(M)    2450.00
 P/E                       104.93
 Market Cap(B)             150.92
 dtype: float64, 'GOOG': Closing price             1133.43
 EPS                         36.05
 Shares  Outstanding(M)     335.83
 Beta                         0.87
 P/E                         31.44
 Market Cap(B)              380.64
 dtype: float64, 'TWTR': Closing price             65.25
 EPS                       -0.30
 Shares Outstanding(M)    555.20
 Market Cap(B)         

In [99]:
stockDF=pd.DataFrame(stockSummaries); stockDF

AAPL    AMZN       FB     GOOG    TWTR     YHOO
Beta                      0.84    0.52      NaN     0.87     NaN     0.66
Closing price           501.53  346.15    61.48  1133.43   65.25    34.90
EPS                      40.32    0.59     0.59    36.05   -0.30     1.27
Market Cap(B)           447.59  158.88   150.92   380.64   36.23    35.36
P/E                      12.44  589.80   104.93    31.44     NaN    27.48
Shares  Outstanding(M)     NaN     NaN      NaN   335.83     NaN      NaN
Shares Outstanding(M)   892.45  459.00  2450.00      NaN  555.20  1010.00

In [100]:
stockDF=pd.DataFrame(stockSummaries,
        index=['Closing price','EPS','Shares Outstanding(M)',
               'P/E', 'Market Cap(B)','Beta']);stockDF


AAPL    AMZN       FB     GOOG    TWTR     YHOO
Closing price          501.53  346.15    61.48  1133.43   65.25    34.90
EPS                     40.32    0.59     0.59    36.05   -0.30     1.27
Shares Outstanding(M)  892.45  459.00  2450.00      NaN  555.20  1010.00
P/E                     12.44  589.80   104.93    31.44     NaN    27.48
Market Cap(B)          447.59  158.88   150.92   380.64   36.23    35.36
Beta                     0.84    0.52      NaN     0.87     NaN     0.66

In [102]:
stockDF=pd.DataFrame(stockSummaries,
        index=['Closing price','EPS','Shares Outstanding(M)',
               'P/E', 'Market Cap(B)','Beta'],     
        columns=['FB','TWTR','SCNW'])
stockDF

FB    TWTR SCNW
Closing price            61.48   65.25  NaN
EPS                       0.59   -0.30  NaN
Shares Outstanding(M)  2450.00  555.20  NaN
P/E                     104.93     NaN  NaN
Market Cap(B)           150.92   36.23  NaN
Beta                       NaN     NaN  NaN

In [106]:
np.random.seed(100) 
ar11=np.random.rand(3); ar11

array([ 0.54340494,  0.27836939,  0.42451759])

In [107]:
#np.random.seed(100) 
ar12=np.random.rand(5); ar12

array([ 0.84477613,  0.00471886,  0.12156912,  0.67074908,  0.82585276])

In [108]:
ar13=np.empty((3,2)); ar13

array([[  4.94065646e-324,   4.94065646e-324],
       [  4.94065646e-324,   4.94065646e-324],
       [  4.94065646e-324,   4.94065646e-324]])

In [111]:
import calendar as cal
monthNames=[cal.month_name[i] for i in np.arange(1,6)]
months=pd.Series(np.arange(1,6),index=monthNames);months

January     1
February    2
March       3
April       4
May         5
dtype: int64

In [112]:
mIdx = pd.MultiIndex(levels=[['US', 'China'],    
                            [1990,2000, 2010]],
                     labels=[[1,1,1,0,0,0],[0,1,2,0,1,2]])
mIdx


MultiIndex(levels=[[u'US', u'China'], [1990, 2000, 2010]],
           labels=[[1, 1, 1, 0, 0, 0], [0, 1, 2, 0, 1, 2]])

In [113]:
ChinaUSDF = pd.DataFrame({'Population(M)' : [1133.68, 1266.83, 1339.72, 
                                                        249.62, 282.16,309.35], 
                                     'GDB($B)': [390.28, 1198.48, 6988.47, 8900,12680,14940]}, 
                          index=mIdx)
ChinaUSDF


GDB($B)  Population(M)
China 1990    390.28        1133.68
      2000   1198.48        1266.83
      2010   6988.47        1339.72
US    1990   8900.00         249.62
      2000  12680.00         282.16
      2010  14940.00         309.35

In [114]:
ChinaUSDF.to_panel()


<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 2 (major_axis) x 3 (minor_axis)
Items axis: GDB($B) to Population(M)
Major_axis axis: US to China
Minor_axis axis: 1990 to 2010

In [116]:
ChinaUSDF = pd.DataFrame({'Population(M)' : [1133.68,   
                                                       1266.83, 
                                                       1339.72, 
                                                        249.62,         
                                                        282.16,
                                                        309.35], 
                                     'GDB($B)': [390.28, 1198.48, 
                                                 6988.47, 8900,
                                                 12680,14940]}, 
                          index=mIdx)
ChinaUSDF


GDB($B)  Population(M)
China 1990    390.28        1133.68
      2000   1198.48        1266.83
      2010   6988.47        1339.72
US    1990   8900.00         249.62
      2000  12680.00         282.16
      2010  14940.00         309.35